// <auto-generated />
using System;
using Hotelio.Modules.Availability.Infrastructure.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotelio.Modules.Availability.Infrastructure.Migrations
{
    [DbContext(typeof(ResourceDbContext))]
    partial class ResourceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("availability")
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hotelio.Modules.Availability.Domain.Model.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("resource_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookId");

                    b.HasIndex("resource_id");

                    b.ToTable("Book", "availability");
                });

            modelBuilder.Entity("Hotelio.Modules.Availability.Domain.Model.Resource", b =>
                {
                    b.Property<Guid>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("_groupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("group_id");

                    b.Property<bool>("_isActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("_type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("_id");

                    b.ToTable("Resources", "availability");
                });

            modelBuilder.Entity("Hotelio.Modules.Availability.Domain.Model.Book", b =>
                {
                    b.HasOne("Hotelio.Modules.Availability.Domain.Model.Resource", null)
                        .WithMany("_books")
                        .HasForeignKey("resource_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hotelio.Modules.Availability.Domain.Model.Resource", b =>
                {
                    b.Navigation("_books");
                });
#pragma warning restore 612, 618
        }
    }
}
