services:
  hotelio:
    image: hotelio.bootstrapper
    build:
      context: .
      dockerfile: src/Bootstrapper/Hotelio.Bootstrapper/Dockerfile
    depends_on:
      - dbsql
    ports:
      - "7099:80"

  dbsql:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
    ports:
      - 1433:1433

  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    ports:
      - 27017:27017
        
  #migrate:
    #build:
      #context: .
      #dockerfile: src/Bootstrapper/Hotelio.Bootstrapper/Dockerfile.migrate
    #depends_on:
      #- dbsql
    #environment:
      #ConnectionStrings__Default: "Server=dbsql;Database=HotelioDb;User=sa;Password=Your_password123;"